# Generated by Django 4.1.1 on 2022-10-02 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Названием организации')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефоном')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН организации')),
                ('data_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_carrier', models.BooleanField(default=False, verbose_name='Перевозчик')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('object', main.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_city', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=150)),
                ('address_city_to', models.CharField(max_length=50)),
                ('address_street_to', models.CharField(max_length=100)),
                ('full_address_to', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=100)),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('is_payments', models.BooleanField(blank=True, default=False, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_complete', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_author', to=settings.AUTH_USER_MODEL)),
                ('company_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
