# Generated by Django 4.1.1 on 2022-09-25 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('company_type', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('data_registration', models.DateTimeField(auto_now_add=True)),
                ('is_carrier', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('object', main.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_city', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=100)),
                ('address_city_to', models.CharField(max_length=50)),
                ('address_street_to', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_payments', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_complete', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
