# Generated by Django 4.1.1 on 2022-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_street_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
