# Generated by Django 4.1.1 on 2022-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_data_complete_order_data_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
