# Generated by Django 4.1.1 on 2022-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Названием организации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_type',
            field=models.CharField(choices=[('ИП', 'ИП'), ('ООО', 'ООО')], max_length=10, verbose_name='Типом организации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефоном'),
        ),
    ]
