# Generated by Django 4.1.1 on 2022-10-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_order_carrier_id_remove_order_wait_list_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='order_wait_list',
            name='order_in_w_list',
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_carrier', to='main.order_wait_list'),
        ),
        migrations.AddField(
            model_name='order_wait_list',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_in_w_list', to='main.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
