# Generated by Django 4.1.1 on 2022-10-04 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_company_id_order_company_remove_order_carrier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier_id',
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_carrier', to=settings.AUTH_USER_MODEL),
        ),
    ]
