# Generated by Django 4.1.1 on 2022-10-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_is_hidden_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_wait_list',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Выбрана заказчиком'),
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_carrier', to='main.order_wait_list'),
        ),
    ]
